$(document).ready(function(){
			$('.image').mouseenter(function(){
				$('.image').hide();
				$('.image2').show();
			});
			$('.image2').mouseleave(function(){
				$('.image2').hide();
				$('.image').show();
			});
			
			$('.image3').mouseenter(function(){
				$('.image3').hide();
				$('.image4').show();
			});
			$('.image4').mouseleave(function(){
				$('.image4').hide();
				$('.image3').show();
			});
			$('.image5').mouseenter(function(){
				$('.image5').hide();
				$('.image6').show();
			});
			$('.image6').mouseleave(function(){
				$('.image6').hide();
				$('.image5').show();
			});
			$('.image7').mouseenter(function(){
				$('.image7').hide();
				$('.image8').show();
			});
			$('.image8').mouseleave(function(){
				$('.image8').hide();
				$('.image7').show();
			});
			$('.image9').mouseenter(function(){
				$('.image9').hide();
				$('.image10').show();
			});
			$('.image10').mouseleave(function(){
				$('.image10').hide();
				$('.image9').show();
			});
			$('.image11').mouseenter(function(){
				$('.image11').hide();
				$('.image12').show();
			});
			$('.image12').mouseleave(function(){
				$('.image12').hide();
				$('.image11').show();
			});
		});